import {
  formatCount,
  formatCurrencyCompact,
  formatLeaguePosition,
  formatPercent,
} from "../shared/formatters";

const sumAggregation = { type: "sum" };
const averageAggregation = { type: "average" };
const latestAggregation = { type: "latest" };
const weightedRatioAggregation = {
  type: "weighted-ratio",
  numeratorAccessor: (row) => row.finance.staffCostsOriginal,
  denominatorAccessor: (row) => row.finance.revenueOriginal,
};

export const metricRegistry = {
  grossTransferSpend: {
    id: "grossTransferSpend",
    label: "Gross transfer spend",
    shortLabel: "Gross spend",
    category: "transfers",
    description: "Total transfer fees paid across the selected period.",
    sourceType: "Transfermarkt club transfer pages",
    getValue: (row) => row.transfers.grossSpendEur,
    formatValue: (value) => formatCurrencyCompact(value, "EUR"),
    axisTick: (value) => `${Math.round(value / 1_000_000)}m`,
    aggregation: sumAggregation,
    higherIsBetter: true,
    compareEnabled: true,
    profileEnabled: true,
  },
  transferIncome: {
    id: "transferIncome",
    label: "Transfer income",
    shortLabel: "Income",
    category: "transfers",
    description: "Total transfer fees received across the selected period.",
    sourceType: "Transfermarkt club transfer pages",
    getValue: (row) => row.transfers.incomeEur,
    formatValue: (value) => formatCurrencyCompact(value, "EUR"),
    axisTick: (value) => `${Math.round(value / 1_000_000)}m`,
    aggregation: sumAggregation,
    higherIsBetter: true,
    compareEnabled: true,
    profileEnabled: true,
  },
  netTransferSpend: {
    id: "netTransferSpend",
    label: "Net transfer spend",
    shortLabel: "Net spend",
    category: "transfers",
    description: "Gross transfer spend minus transfer income.",
    sourceType: "Transfermarkt club transfer pages",
    getValue: (row) => row.transfers.netSpendEur,
    formatValue: (value) => formatCurrencyCompact(value, "EUR"),
    axisTick: (value) => `${Math.round(value / 1_000_000)}m`,
    aggregation: sumAggregation,
    higherIsBetter: true,
    compareEnabled: true,
    profileEnabled: true,
  },
  incomingTransfers: {
    id: "incomingTransfers",
    label: "Incoming transfers",
    shortLabel: "Incoming",
    category: "transfers",
    description: "Incoming player deals recorded in each season.",
    sourceType: "Transfermarkt club transfer pages",
    getValue: (row) => row.transfers.incomingCount,
    formatValue: (value) => formatCount(value),
    axisTick: (value) => `${Math.round(value)}`,
    aggregation: sumAggregation,
    higherIsBetter: true,
    compareEnabled: true,
    profileEnabled: true,
  },
  revenue: {
    id: "revenue",
    label: "Revenue",
    shortLabel: "Revenue",
    category: "finances",
    description: "Official club revenue in reported currency. All currently available Big Six finance rows are in GBP.",
    sourceType: "Official annual reports and filings",
    getValue: (row) => row.finance.revenueOriginal,
    formatValue: (value) => formatCurrencyCompact(value, "GBP"),
    axisTick: (value) => `£${Math.round(value / 1_000_000)}m`,
    aggregation: sumAggregation,
    higherIsBetter: true,
    compareEnabled: true,
    profileEnabled: true,
  },
  staffCosts: {
    id: "staffCosts",
    label: "Staff costs",
    shortLabel: "Staff costs",
    category: "finances",
    description: "Official staff costs from club accounts. This is not the same metric as estimated player wages.",
    sourceType: "Official annual reports and filings",
    getValue: (row) => row.finance.staffCostsOriginal,
    formatValue: (value) => formatCurrencyCompact(value, "GBP"),
    axisTick: (value) => `£${Math.round(value / 1_000_000)}m`,
    aggregation: sumAggregation,
    higherIsBetter: false,
    compareEnabled: true,
    profileEnabled: true,
  },
  staffCostToRevenueRatio: {
    id: "staffCostToRevenueRatio",
    label: "Staff costs / revenue",
    shortLabel: "Staff / revenue",
    category: "finances",
    description: "Official staff costs divided by revenue, calculated in reported currency where both values are available.",
    sourceType: "Official annual reports and filings",
    getValue: (row) => row.finance.staffCostToRevenueRatio,
    formatValue: (value) => formatPercent(value),
    axisTick: (value) => `${Math.round(value * 100)}%`,
    aggregation: weightedRatioAggregation,
    higherIsBetter: false,
    compareEnabled: true,
    profileEnabled: true,
  },
  profitBeforeTax: {
    id: "profitBeforeTax",
    label: "Profit before tax",
    shortLabel: "Profit before tax",
    category: "finances",
    description: "Reported profit or loss before tax. Period comparisons sum the selected club-season observations.",
    sourceType: "Official annual reports and filings",
    getValue: (row) => row.finance.profitBeforeTaxOriginal,
    formatValue: (value) => formatCurrencyCompact(value, "GBP"),
    axisTick: (value) => `£${Math.round(value / 1_000_000)}m`,
    aggregation: sumAggregation,
    higherIsBetter: true,
    compareEnabled: true,
    profileEnabled: true,
  },
  netDebt: {
    id: "netDebt",
    label: "Net debt",
    shortLabel: "Net debt",
    category: "finances",
    description: "End-of-period net debt. Comparisons use the latest comparable season in the selected range.",
    sourceType: "Official annual reports and filings",
    getValue: (row) => row.finance.netDebtOriginal,
    formatValue: (value) => formatCurrencyCompact(value, "GBP"),
    axisTick: (value) => `£${Math.round(value / 1_000_000)}m`,
    aggregation: latestAggregation,
    higherIsBetter: false,
    compareEnabled: true,
    profileEnabled: true,
  },
  points: {
    id: "points",
    label: "Points",
    shortLabel: "Points",
    category: "performance",
    description: "Premier League points from the season table layer.",
    sourceType: "Season table exports",
    getValue: (row) => row.performance.points,
    formatValue: (value) => formatCount(value),
    axisTick: (value) => `${Math.round(value)}`,
    aggregation: sumAggregation,
    higherIsBetter: true,
    compareEnabled: true,
    profileEnabled: true,
  },
  leaguePosition: {
    id: "leaguePosition",
    label: "League position",
    shortLabel: "League position",
    category: "performance",
    description: "Final Premier League position. Lower is better.",
    sourceType: "Season table exports",
    getValue: (row) => row.performance.leaguePosition,
    formatValue: (value) => formatLeaguePosition(value),
    axisTick: (value) => `${Math.round(value)}`,
    aggregation: averageAggregation,
    higherIsBetter: false,
    compareEnabled: true,
    profileEnabled: true,
    reverseAxis: true,
  },
  trophies: {
    id: "trophies",
    label: "Trophies",
    shortLabel: "Trophies",
    category: "performance",
    description: "Major trophies captured in the achievements layer.",
    sourceType: "Transfermarkt achievements",
    getValue: (row) => row.achievements.majorTrophyCount,
    formatValue: (value) => formatCount(value),
    axisTick: (value) => `${Math.round(value)}`,
    aggregation: sumAggregation,
    higherIsBetter: true,
    compareEnabled: true,
    profileEnabled: true,
  },
  rawPlayerCost: {
    id: "rawPlayerCost",
    label: "Raw player cost",
    shortLabel: "Raw player cost",
    category: "efficiency",
    description: "Will unlock once the wage layer is populated cleanly enough to combine with transfer spending.",
    sourceType: "Future combined wage and transfer model",
    getValue: (row) => row.efficiency.rawPlayerCostEur,
    formatValue: (value) => formatCurrencyCompact(value, "EUR"),
    axisTick: (value) => `${Math.round(value / 1_000_000)}m`,
    aggregation: sumAggregation,
    higherIsBetter: false,
    compareEnabled: false,
    profileEnabled: true,
  },
  costPerPoint: {
    id: "costPerPoint",
    label: "Cost per point",
    shortLabel: "Cost per point",
    category: "efficiency",
    description: "Will unlock once raw player cost becomes reliable.",
    sourceType: "Future combined wage and transfer model",
    getValue: (row) => row.efficiency.costPerPoint,
    formatValue: (value) => formatCurrencyCompact(value, "EUR"),
    axisTick: (value) => `${Math.round(value / 1_000_000)}m`,
    aggregation: averageAggregation,
    higherIsBetter: false,
    compareEnabled: false,
    profileEnabled: true,
  },
};

export function getMetric(metricId) {
  return metricRegistry[metricId];
}

export const compareMetricGroups = [
  {
    id: "transfers",
    label: "Transfers",
    metricIds: ["grossTransferSpend", "transferIncome", "netTransferSpend"],
  },
  {
    id: "finances",
    label: "Finances",
    metricIds: ["revenue", "staffCosts", "staffCostToRevenueRatio", "profitBeforeTax", "netDebt"],
  },
  {
    id: "performance",
    label: "Performance",
    metricIds: ["points", "leaguePosition", "trophies"],
  },
  {
    id: "efficiency",
    label: "Efficiency",
    metricIds: ["rawPlayerCost", "costPerPoint"],
  },
];

export const profileSnapshotMetricIds = [
  "revenue",
  "netTransferSpend",
  "staffCostToRevenueRatio",
  "leaguePosition",
];
